package io.github.thrhead.taplog.core.domain

enum class Behavior { MOMENT, COUNTER, DURATION, STATE }
enum class Lifecycle { ACTIVE, ARCHIVED }
enum class Source { APP, WIDGET, QUICK_SETTINGS, NFC, NATURAL_LANGUAGE }
typealias EventSource = Source
enum class DurationStatus { OPEN, COMPLETED, INCOMPLETE }
enum class BindingStatus { ACTIVE, ORPHANED }
enum class ResultReason {
    INACTIVE_SCOPE, UNLINKED_RELATIONSHIP, BEHAVIOR_MISMATCH, INVALID_QUANTITY,
    UNIT_MISMATCH, NEGATIVE_DURATION, OPEN_DURATION_EXISTS, TERMINAL_DURATION,
    MISSING_STATE_GROUP, STALE_REVISION, STALE_DATASET_GENERATION,
    STALE_SCOPE_CONTEXT, CONFIRMATION_REQUIRED, PERMANENT_DELETE_IMPACT,
    INVALID_REQUEST, STORAGE_FAILURE
}
